name: Dockernize Coska chat backend service and push the image to AWS ECR repository

on:
  workflow_dispatch:
    branches:
      - develop
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: run maven build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

          # for DDNS
          google_domains_hostname: ${{ vars.GOOGLE_DOMAINS_HOSTNAME }}
          google_domains_username: ${{ secrets.GOOGLE_DOMAINS_USERNAME }}
          google_domains_password: ${{ secrets.GOOGLE_DOMAINS_PASSWORD }}

          # for SSL certificate
          coska_com_p12_store_password: ${{ secrets.COSKA_COM_P12_STORE_PASSWORD }}
          coska_com_p12_key_alias: ${{ secrets.COSKA_COM_P12_KEY_ALIAS }}
          coska_com_p12_path: ${{ secrets.COSKA_COM_P12_PATH }}

          # for Cognito
          cognito_jwt_url: ${{ secrets.COGNITO_JWT_URL }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Publish to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          mkdir -p cert
          aws s3 cp s3://coska-chat-backend/coska.com.p12 cert/
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"